server.port=${SERVER_PORT:8084}
# Correct JDBC format for PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7bjbv1r0fns739aiq50-a:5432/user_service_8j9j?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
eureka.client.service-url.defaultZone=${EUREKA_URL}
